### ISSUE TITLE
 The SUID sandbox helper binary was found, but is not configured correctly

### ISSUE THREAD

**Issue by martinpescador** [oxen-io/session-desktop#1058]
**Describe the bug**

session-desktop fails to run in LMDE 4:  The SUID sandbox helper binary was found, but is not configured correctly

**To Reproduce**

run app:
./session-messenger-desktop-linux-x86_64-1.0.6.AppImage

**Screenshots or Logs**

$ ./session-messenger-desktop-linux-x86_64-1.0.6.AppImage 
[21626:0407/003239.030411:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_sessionDmUYQ/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap (core dumped)

**Other information (please complete the following information):**

* Device: pc
* OS: LMDE 4 / Debian Buster
* Session Version:  1.0.6.AppImage
* Perhaps see: https://github.com/signalapp/Signal-Desktop/issues/3536

**Comment by KeeJef** [comment]
You should be able to run with ```--no-sandbox``` for now

**Comment by shamilbi** [comment]
Run with --no-sandbox:

Set Windows Application User Model ID (AUMID) { appUserModelId: 'com.loki-project.messenger-desktop' }
NODE_ENV production
NODE_APP_INSTANCE undefined
NODE_CONFIG_DIR /tmp/.mount_sessiofycRdT/resources/app.asar/config
NODE_CONFIG {}
userData: /home/USER/.config/Session
config/get: Did not find user config file, cache is now empty object
config/get: Did not find ephemeral config file, cache is now empty object
Unhandled Error: Error: /tmp/.org.chromium.Chromium.6l0H6P: failed to map segment from shared object
    at process.func (electron/js2c/asar.js:140:31)
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1016:18)
    at Object.func (electron/js2c/asar.js:140:31)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:816:32)
    at Module._load (internal/modules/cjs/loader.js:728:14)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:853:19)
Unhandled Error: Error: /tmp/.org.chromium.Chromium.6l0H6P: failed to map segment from shared object
    at process.func (electron/js2c/asar.js:140:31)
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1016:18)
    at Object.func (electron/js2c/asar.js:140:31)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:816:32)
    at Module._load (internal/modules/cjs/loader.js:728:14)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:853:19)
Unhandled Error Error: /tmp/.org.chromium.Chromium.6l0H6P: failed to map segment from shared object
    at process.func (electron/js2c/asar.js:140:31)
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1016:18)
    at Object.func (electron/js2c/asar.js:140:31)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:816:32)
    at Module._load (internal/modules/cjs/loader.js:728:14)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:853:19)

Device: pc
OS: Slackware x86_64
Session Version: session-desktop-linux-x86_64-1.4.8.AppImage

**Comment by Bilb** [comment]
Looks to be coming from signal and a wordaround is given there.
https://github.com/signalapp/Signal-Desktop/issues/2641#issuecomment-411465969
