### ISSUE TITLE
send failed in v1.1.2

### ISSUE THREAD

**Issue by dang102** [oxen-io/session-desktop#1272]
```
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Session/1.1.2 Chrome/80.0.3987.158 Electron/8.2.0 Safari/537.36 node/12.13.0 env/production
INFO  2020-07-19T18:52:46.685Z app ready
INFO  2020-07-19T18:52:46.686Z starting version 1.1.2
INFO  2020-07-19T18:52:46.977Z updateSchema: Current schema version: 21; Most recent schema version: 11; SQLite version: 3.30.1; SQLCipher version: 4.3.0 community;
INFO  2020-07-19T18:52:46.986Z updateLokiSchema: Current loki schema version: 6; Most recent schema version: 6;
INFO  2020-07-19T18:52:47.037Z Ensure attachments directory exists
INFO  2020-07-19T18:52:47.047Z auto-update: starting checks...
INFO  2020-07-19T18:52:47.431Z Initializing BrowserWindow config: {"show":true,"width":1366,"height":704,"minWidth":880,"minHeight":600,"autoHideMenuBar":false,"backgroundColor":"#fff","webPreferences":{"nodeIntegration":false,"nodeIntegrationInWorker":false,"contextIsolation":false,"preload":"[REDACTED]/app.asar/preload.js","nativeWindowOpen":true,"spellcheck":true},"icon":"[REDACTED]/app.asar/images/session/icon_64.png","maximized":false,"x":0,"y":24}
WARN  2020-07-19T18:52:47.895Z (electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
INFO  2020-07-19T18:52:48.092Z spellcheck: user locale: en-US
INFO  2020-07-19T18:52:48.093Z spellcheck: available spellchecker languages:  ["af","bg","ca","cs","cy","da","de","el","en-AU","en-CA","en-GB","en-US","es","es-419","es-AR","es-ES","es-MX","es-US","et","fa","fo","fr","he","hi","hr","hu","hy","id","it","ko","lt","lv","nb","nl","pl","pt-BR","pt-PT","ro","ru","sh","sk","sl","sq","sr","sv","ta","tg","tr","uk","vi"]
INFO  2020-07-19T18:52:48.093Z spellcheck: setting languages to:  ["en-US"]
INFO  2020-07-19T18:52:53.771Z pre-main prep time: 2 ms
INFO  2020-07-19T18:52:53.839Z LokiAppDotNetAPI registered server https://file.getsession.org
INFO  2020-07-19T18:52:53.921Z background page reloaded
INFO  2020-07-19T18:52:53.922Z environment: production
INFO  2020-07-19T18:52:54.440Z Storage fetch
INFO  2020-07-19T18:52:54.443Z LokiSnodeAPI::buildNewOnionPaths - building new onion paths
INFO  2020-07-19T18:52:54.868Z Starting background data migration. Target version: 10
INFO  2020-07-19T18:52:54.870Z ConversationController: starting initial fetch
INFO  2020-07-19T18:52:55.106Z SignalProtocolStore: Finished caching identityKeys data
INFO  2020-07-19T18:52:55.114Z ConversationController: done with initial fetch
INFO  2020-07-19T18:52:55.114Z SignalProtocolStore: Finished caching sessions data
INFO  2020-07-19T18:52:55.115Z SignalProtocolStore: Finished caching preKeys data
INFO  2020-07-19T18:52:55.116Z SignalProtocolStore: Finished caching signedPreKeys data
INFO  2020-07-19T18:52:55.118Z Cleanup: starting...
INFO  2020-07-19T18:52:55.120Z Cleanup: Found 0 messages for cleanup
INFO  2020-07-19T18:52:55.120Z Cleanup: complete
INFO  2020-07-19T18:52:55.120Z listening for registration events
WARN  2020-07-19T18:52:55.123Z (electron) 'setAutoHideMenuBar function' is deprecated and will be removed. Please use 'autoHideMenuBar property' instead.
INFO  2020-07-19T18:52:55.124Z Next signed key rotation scheduled for 2020-07-21T18:41:37.664Z
INFO  2020-07-19T18:52:55.125Z connect
INFO  2020-07-19T18:52:55.126Z getAllFromCache
INFO  2020-07-19T18:52:55.126Z Registering HomeServer https://file.getsession.org
INFO  2020-07-19T18:52:55.127Z LokiAppDotNetAPI registered server https://file.getsession.org
INFO  2020-07-19T18:52:55.134Z Delaying expire banner determination for 5s
ERROR 2020-07-19T18:52:55.602Z Top-level unhandled promise rejection: TypeError: Cannot read property 'key' of undefined
INFO  2020-07-19T18:52:55.607Z loki_snode_api::tryGetSnodeListFromLokidSeednode - https://storage.seed1.loki.network/ returned 1176 snodes
INFO  2020-07-19T18:52:55.608Z LokiSnodeAPI::refreshRandomPool - Refreshed random snode pool with 1176 snodes
INFO  2020-07-19T18:52:55.624Z getAllFromCache loaded 0 saved envelopes
ERROR 2020-07-19T18:52:55.626Z Top-level unhandled promise rejection: Error: Invalid SignalProtocolAddress string
INFO  2020-07-19T18:52:55.629Z Built 3 onion paths [{"path":[{"ip":"94.23.195.185","port":23032,"pubkey_x25519":"f3d365cd2a081d06117362e7ec1cefaf87a38faeffe61682e66eacca21fbd574","pubkey_ed25519":"18a40bfe7818d66d1757719e9faaca4be5274eef891cad751f34865d817a86a9","version":""},{"ip":"51.15.197.67","port":22021,"pubkey_x25519":"a8063dbc6a1147140ef67ed00aa389ac97db019074738ad16efe8b49e7b4a86f","pubkey_ed25519":"cebb9781931a86dd866a78d3c02615eaae22c8b247e92ac2040ca7b1638937b8","version":""},{"ip":"116.203.149.171","port":22021,"pubkey_x25519":"bf7dce39030ce5f2029f2149649f84048accbb3ea63b74bcb556a1b0d4b10f54","pubkey_ed25519":"c0a107e0ef9af1485b31782237a71d419f4ffd0be17b111e39ecda29eef46de7","version":""}],"bad":false},{"path":[{"ip":"68.183.236.72","port":22021,"pubkey_x25519":"0ea63d99abcc85d1c810cf0b36df4193913e0d13033a50d6a8dfa4f830ec7f32","pubkey_ed25519":"028a954d7551520416b4e44caf8fa62fe262facd4881dcc9eb3dce80eb3a7401","version":""},{"ip":"45.77.30.118","port":22021,"pubkey_x25519":"33b9f40b8fa5a3707ca8b4ced775053392ef7cdaa1ee2b6f51224e60d56df864","pubkey_ed25519":"f7c99a450e99b89192ea7a4efdd6248cff4f4e5aa468bff252c62f06c61cbcdc","version":""},{"ip":"149.56.141.169","port":22021,"pubkey_x25519":"d5f67ea6ca5ba3d3368eec3d02fc0a3df3b73b4bbebaaa41ab94420ee2a7235d","pubkey_ed25519":"11edd12a6f29011a1beb5b245a06b16548f2796eec4057a6c191700ffa780f5b","version":""}],"bad":false},{"path":[{"ip":"95.179.183.42","port":22021,"pubkey_x25519":"509aebd819280589943f3128c22967b93fbd2b29b0e63b6adb273fd14c48125d","pubkey_ed25519":"483f9dc1c47d72d73cab54b74da31c53111f1ed886b93e7bc1fca57d3ef677fd","version":""},{"ip":"167.99.6.6","port":22021,"pubkey_x25519":"19caa57d4788ea957ceb0dc7324e9ae793c5a9c58841630ace15f4c1037b770c","pubkey_ed25519":"a1e6423b87773aba825b8883bd43169b130855a44e378a06a61e2b1f50e6f331","version":""},{"ip":"213.136.86.8","port":52021,"pubkey_x25519":"fd43e7d25ace4ee19345e04553adfe470566f0d6bbb1c836d770d8a4e7c9d939","pubkey_ed25519":"5fc390456f0e98ca45e8d5654d10ddaf07b1f903afb01b1d122a48cafd0a388a","version":""}],"bad":false}]
WARN  2020-07-19T18:52:56.093Z (electron) 'setBadgeCount function' is deprecated and will be removed. Please use 'badgeCount property' instead.
INFO  2020-07-19T18:52:56.871Z expire:::setClockParams - Clock difference -1
ERROR 2020-07-19T18:52:58.003Z Top-level unhandled promise rejection: TypeError: Illegal str: Not a string
INFO  2020-07-19T18:53:03.154Z Conversation [REDACTED] took 167 milliseconds to load
INFO  2020-07-19T18:53:11.596Z Send pre-checks took 25 milliseconds
INFO  2020-07-19T18:53:11.619Z Sending message to conversation [REDACTED] with timestamp 1595184791619
ERROR 2020-07-19T18:53:12.680Z Message.saveErrors: null SendMessageNetworkError: Network is not available
    at file://[REDACTED]/app.asar/js/models/conversations.js:1332:27
    at Function._.map._.collect (file://[REDACTED]/app.asar/js/components.js:15535:24)
    at Backbone.Collection.map (file://[REDACTED]/app.asar/js/components.js:17110:25)
    at file://[REDACTED]/app.asar/js/models/conversations.js:1331:49
INFO  2020-07-19T19:06:38.933Z app ready
INFO  2020-07-19T19:06:38.933Z starting version 1.1.2
INFO  2020-07-19T19:06:38.973Z updateSchema: Current schema version: 21; Most recent schema version: 11; SQLite version: 3.30.1; SQLCipher version: 4.3.0 community;
INFO  2020-07-19T19:06:38.977Z updateLokiSchema: Current loki schema version: 6; Most recent schema version: 6;
INFO  2020-07-19T19:06:39.017Z Ensure attachments directory exists
INFO  2020-07-19T19:06:39.023Z auto-update: starting checks...
INFO  2020-07-19T19:06:39.062Z Initializing BrowserWindow config: {"show":true,"width":1366,"height":704,"minWidth":880,"minHeight":600,"autoHideMenuBar":false,"backgroundColor":"#fff","webPreferences":{"nodeIntegration":false,"nodeIntegrationInWorker":false,"contextIsolation":false,"preload":"[REDACTED]/app.asar/preload.js","nativeWindowOpen":true,"spellcheck":true},"icon":"[REDACTED]/app.asar/images/session/icon_64.png","maximized":false,"x":0,"y":24}
WARN  2020-07-19T19:06:39.094Z (electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
INFO  2020-07-19T19:06:39.108Z spellcheck: user locale: en-US
INFO  2020-07-19T19:06:39.108Z spellcheck: available spellchecker languages:  ["af","bg","ca","cs","cy","da","de","el","en-AU","en-CA","en-GB","en-US","es","es-419","es-AR","es-ES","es-MX","es-US","et","fa","fo","fr","he","hi","hr","hu","hy","id","it","ko","lt","lv","nb","nl","pl","pt-BR","pt-PT","ro","ru","sh","sk","sl","sq","sr","sv","ta","tg","tr","uk","vi"]
INFO  2020-07-19T19:06:39.108Z spellcheck: setting languages to:  ["en-US"]
INFO  2020-07-19T19:06:40.321Z pre-main prep time: 3 ms
INFO  2020-07-19T19:06:40.391Z LokiAppDotNetAPI registered server https://file.getsession.org
INFO  2020-07-19T19:06:40.436Z background page reloaded
INFO  2020-07-19T19:06:40.436Z environment: production
INFO  2020-07-19T19:06:40.671Z Storage fetch
INFO  2020-07-19T19:06:40.674Z LokiSnodeAPI::buildNewOnionPaths - building new onion paths
INFO  2020-07-19T19:06:40.954Z Starting background data migration. Target version: 10
INFO  2020-07-19T19:06:40.955Z ConversationController: starting initial fetch
INFO  2020-07-19T19:06:41.188Z SignalProtocolStore: Finished caching identityKeys data
INFO  2020-07-19T19:06:41.202Z ConversationController: done with initial fetch
INFO  2020-07-19T19:06:41.203Z SignalProtocolStore: Finished caching sessions data
INFO  2020-07-19T19:06:41.208Z SignalProtocolStore: Finished caching preKeys data
INFO  2020-07-19T19:06:41.360Z SignalProtocolStore: Finished caching signedPreKeys data
INFO  2020-07-19T19:06:41.364Z Cleanup: starting...
INFO  2020-07-19T19:06:41.367Z Cleanup: Found 0 messages for cleanup
INFO  2020-07-19T19:06:41.368Z Cleanup: complete
INFO  2020-07-19T19:06:41.368Z listening for registration events
WARN  2020-07-19T19:06:41.376Z (electron) 'setAutoHideMenuBar function' is deprecated and will be removed. Please use 'autoHideMenuBar property' instead.
INFO  2020-07-19T19:06:41.377Z Next signed key rotation scheduled for 2020-07-21T18:41:37.664Z
INFO  2020-07-19T19:06:41.378Z connect
INFO  2020-07-19T19:06:41.381Z getAllFromCache
INFO  2020-07-19T19:06:41.382Z Registering HomeServer https://file.getsession.org
INFO  2020-07-19T19:06:41.383Z LokiAppDotNetAPI registered server https://file.getsession.org
INFO  2020-07-19T19:06:41.403Z Delaying expire banner determination for 5s
ERROR 2020-07-19T19:06:41.886Z Top-level unhandled promise rejection: TypeError: Cannot read property 'key' of undefined
INFO  2020-07-19T19:06:41.896Z getAllFromCache loaded 0 saved envelopes
ERROR 2020-07-19T19:06:41.897Z Top-level unhandled promise rejection: Error: Invalid SignalProtocolAddress string
INFO  2020-07-19T19:06:41.914Z loki_snode_api::tryGetSnodeListFromLokidSeednode - https://storage.seed1.loki.network/ returned 1176 snodes
INFO  2020-07-19T19:06:41.916Z LokiSnodeAPI::refreshRandomPool - Refreshed random snode pool with 1176 snodes
INFO  2020-07-19T19:06:41.926Z Built 3 onion paths [{"path":[{"ip":"94.23.195.185","port":23032,"pubkey_x25519":"f3d365cd2a081d06117362e7ec1cefaf87a38faeffe61682e66eacca21fbd574","pubkey_ed25519":"18a40bfe7818d66d1757719e9faaca4be5274eef891cad751f34865d817a86a9","version":""},{"ip":"116.202.111.205","port":22128,"pubkey_x25519":"0211745d1db94e4bc03fcbb72aab04285ba8250d80505f0b95d6324544b9e542","pubkey_ed25519":"6b50a23cd559873f79801dc47036cf9f4bd293f28bb189488b03fa950e019c2b","version":""},{"ip":"139.162.61.4","port":22021,"pubkey_x25519":"cd1f1169d77a2b9222c774503234778aa587114ecb83b6b16bc87c00c5ed024d","pubkey_ed25519":"fdfe104fcf58ed78ebaac8513c9c71014d9e76d41385b8b830495e32045cb24b","version":""}],"bad":false},{"path":[{"ip":"95.179.183.42","port":22021,"pubkey_x25519":"509aebd819280589943f3128c22967b93fbd2b29b0e63b6adb273fd14c48125d","pubkey_ed25519":"483f9dc1c47d72d73cab54b74da31c53111f1ed886b93e7bc1fca57d3ef677fd","version":""},{"ip":"185.241.6.121","port":22021,"pubkey_x25519":"46d225363cf648a42094d6ece59368511248a51c333eabaf9f3f6669fc541d56","pubkey_ed25519":"f14f9e1e25bfccaa5e63fb3746c7f57178c98db941b64123a1de45f35bba0cd1","version":""},{"ip":"45.77.130.87","port":22021,"pubkey_x25519":"4aa804ef09a06e0159b2dad09b7c13f8e7a5072bc878db53f79f1f45ca005935","pubkey_ed25519":"787acd6beb494f1f8199c063c97d6fc92b95374828266720700474a0712a4e19","version":""}],"bad":false},{"path":[{"ip":"68.183.236.72","port":22021,"pubkey_x25519":"0ea63d99abcc85d1c810cf0b36df4193913e0d13033a50d6a8dfa4f830ec7f32","pubkey_ed25519":"028a954d7551520416b4e44caf8fa62fe262facd4881dcc9eb3dce80eb3a7401","version":""},{"ip":"167.86.86.191","port":22021,"pubkey_x25519":"6a1ebdc2401e7aacd7ff63719c0aa10d751b4502e70643a42f1ac25745773f55","pubkey_ed25519":"67ab847d20e5168ee53d8b4cea33baf52453b46a3dcd5f8b0491664d965f74a0","version":""},{"ip":"116.202.102.93","port":22021,"pubkey_x25519":"bc379cd6d918fc8e8475f965bc622aa0afaa2c9e842969572b696792a9f63259","pubkey_ed25519":"24afc1f9574c0f6c7075732df930ca28ebb4cda0c303c25bcc5b77d9a226e3cf","version":""}],"bad":false}]
WARN  2020-07-19T19:06:42.176Z (electron) 'setBadgeCount function' is deprecated and will be removed. Please use 'badgeCount property' instead.
INFO  2020-07-19T19:06:43.064Z expire:::setClockParams - Clock difference -2
ERROR 2020-07-19T19:06:44.731Z Top-level unhandled promise rejection: TypeError: Illegal str: Not a string
INFO  2020-07-19T19:06:49.034Z Conversation [REDACTED] took 91 milliseconds to load
INFO  2020-07-19T19:06:53.706Z Send pre-checks took 28 milliseconds
INFO  2020-07-19T19:06:53.730Z Sending message to conversation [REDACTED] with timestamp 1595185613730
ERROR 2020-07-19T19:06:54.586Z Message.saveErrors: null SendMessageNetworkError: Network is not available
    at file://[REDACTED]/app.asar/js/models/conversations.js:1332:27
    at Function._.map._.collect (file://[REDACTED]/app.asar/js/components.js:15535:24)
    at Backbone.Collection.map (file://[REDACTED]/app.asar/js/components.js:17110:25)
    at file://[REDACTED]/app.asar/js/models/conversations.js:1331:49
ERROR 2020-07-19T19:08:49.141Z Top-level unhandled promise rejection: TypeError: Cannot read property 'key' of undefined
ERROR 2020-07-19T19:08:49.725Z Top-level unhandled promise rejection: TypeError: Cannot read property 'key' of undefined
ERROR 2020-07-19T19:08:52.573Z Top-level unhandled promise rejection: TypeError: Cannot read property 'key' of undefined
INFO  2020-07-19T19:11:11.016Z Conversation [REDACTED] took 40 milliseconds to load
INFO  2020-07-19T19:11:19.192Z Conversation [REDACTED] took 54 milliseconds to load
INFO  2020-07-19T19:11:20.633Z Conversation [REDACTED] took 36 milliseconds to load
INFO  2020-07-19T19:14:12.268Z Loaded this list of log files from logPath: log.log
```

**Comment by Mikunj** [comment]
@dang102 is this still occurring in the new versions?

**Comment by dang102** [comment]
It looks like you closed the bug report ?  It is still happening I can't run any ver. now ??? not sure what you want me to do ? I real would love to run this but seem I can't !

**Comment by Mikunj** [comment]
This issue is still open, i closed the other one as the main information was in this issue. Does sending still fail even if you try create a new session id?

**Comment by dang102** [comment]
Sent from Outlook<http://aka.ms/weboutlook>Hey It maybe working 1.2.1 just need some one to test it.


________________________________

**Comment by beantaco** [comment]
> It seems that network access to Session seems to be blocked and thus it can't send anything.

I am unable to send messages and it seems to be related to network access.

When I launch Session from a terminal, I see this message appear in the terminal each time I hit the ENTER key in an attempt to send a message:

> "Must have at least 2 good onion paths, actual: 0, attempt #0 fetching more..."

Version: 1.4.5

**Comment by Bilb** [comment]
@beantaco this is probably not the same issue as the first bug report on this issue. 
Could you send me your logs and create a new issue if that's not already the case ?
Are you running behind a proxy ?

**Comment by Bilb** [comment]
@dang102 no news since your message on 1.2.1 saying that it might be working. So I will close this issue for now. Feel free to reopen it if needed
