### ISSUE TITLE
Updated Session - Not working

### ISSUE THREAD

**Issue by starlightromero** [oxen-io/session-desktop#1471]
I updated Session when prompted from the GUI. Session quit, as expected. When I tried to open Session again. I got this error.

```
Unhandled Error
Error: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.org.chromium.Chromium.uQHrLT)
    at process.func (electron/js2c/asar.js:140:31)
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1016:18)
    at Object.func (electron/js2c/asar.js:140:31)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:816:32)
    at Module._load (internal/modules/cjs/loader.js:728:14)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:853:19)
```

**Other information (please complete the following information):**

* Device: Macbook 14,2
* OS: Elementary OS (5.4.0-65-generic)
* Session Version or Git commit hash: Version on 1/31/2021

**Comment by FatBirdie** [comment]
Same here

**Comment by wuweituzi** [comment]
Same situtation on linux. They need to recompile with GLIBC_2.28.

**Comment by KeeJef** [comment]
Were investigating this right now

**Comment by Bilb** [comment]
Can you please download the 1.4.8 and try again please?

**Comment by starlightromero** [comment]
Finished compiling and testing the app. All is well. Salud
