### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by adamwawrzynski** [oxen-io/session-desktop#1885]
**Describe the bug**
I tried to build session according to instruction in [BUILDING.md](https://github.com/oxen-io/session-desktop/blob/clearnet/BUILDING.md) but it throws error.

**To Reproduce**
1. `npm install yarn --no-save`
2. `yarn install --frozen-lockfile`

**Screenshots or Logs**
```bash
yarn install v1.22.11
[1/6] Validating package.json...
[2/6] Resolving packages...
[3/6] Fetching packages...
info fsevents@1.2.11: The platform "linux" is incompatible with this module.
info "fsevents@1.2.11" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/6] Linking dependencies...
warning " > emoji-mart@2.11.2" has incorrect peer dependency "react@^0.14.0 || ^15.0.0-0 || ^16.0.0".
warning " > mic-recorder-to-mp3@2.2.2" has unmet peer dependency "webrtc-adapter@>=4.1.1".
warning "rc-slider > rc-util@4.20.1" has incorrect peer dependency "react@^15.0.0 || ^16.0.0".
warning "rc-slider > rc-util@4.20.1" has incorrect peer dependency "react-dom@^15.0.0 || ^16.0.0".
warning " > react-h5-audio-player@3.2.0" has incorrect peer dependency "react@^16.3.0".
warning " > react-h5-audio-player@3.2.0" has incorrect peer dependency "react-dom@^16.3.0".
warning "react-h5-audio-player > @iconify/react@1.1.3" has incorrect peer dependency "react@^16.0.0".
warning " > react-qr-svg@2.2.1" has incorrect peer dependency "react@>= 0.11.2 < 17.0.0".
warning " > react-redux@7.2.1" has incorrect peer dependency "react@^16.8.3".
warning " > react-virtualized@9.22.3" has incorrect peer dependency "react@^15.3.0 || ^16.0.0-alpha".
warning " > react-virtualized@9.22.3" has incorrect peer dependency "react-dom@^15.3.0 || ^16.0.0-alpha".
warning " > styled-components@5.1.1" has unmet peer dependency "react-is@>= 16.8.0".
warning " > use-hooks@2.0.0-rc.5" has incorrect peer dependency "react@^16.8.0".
warning " > grunt-gitinfo@0.1.7" has incorrect peer dependency "grunt@~0.4.5".
warning " > ts-mock-imports@1.3.0" has incorrect peer dependency "typescript@>=2.6.1 < 4".
warning " > tslint-microsoft-contrib@6.0.0" has incorrect peer dependency "typescript@^2.1.0 || ^3.0.0".
[5/6] Building fresh packages...
[1/8] ⡀ better-sqlite3
[2/8] ⡀ dtrace-provider
[3/8] ⡀ node-sass
[8/8] ⡀ electron
error /home/user/session-desktop/node_modules/better-sqlite3: Command failed.
Exit code: 1
Command: npm run build-release
Arguments: 
Directory: /home/user/session-desktop/node_modules/better-sqlite3
Output:
npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1629835060325-0.6185151674042371/node but npm is using /home/user/.nvm/versions/node/v14.16.0/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> better-sqlite3@7.1.4 build-release /home/user/session-desktop/node_modules/better-sqlite3
> node-gyp rebuild --release

make: Entering directory '/home/user/session-desktop/node_modules/better-sqlite3/build'
  TOUCH b857c92884e9598d609f6be182a2595df7a8e00f.intermediate
  ACTION deps_sqlite3_gyp_locate_sqlite3_target_extract_sqlite3 b857c92884e9598d609f6be182a2595df7a8e00f.intermediate
/home/user/session-desktop/node_modules/better-sqlite3/deps/extract.js:8
process.on('unhandledRejection', (err) => { throw err; });
                                            ^

Error: TAR_BAD_ARCHIVE: Unrecognized archive format
    at Unpack.warn (/home/user/session-desktop/node_modules/better-sqlite3/node_modules/tar/lib/warn-mixin.js:19:40)
    at Unpack.warn (/home/user/session-desktop/node_modules/better-sqlite3/node_modules/tar/lib/unpack.js:189:18)
    at Unpack.<anonymous> (/home/user/session-desktop/node_modules/better-sqlite3/node_modules/tar/lib/parse.js:81:14)
    at Unpack.emit (events.js:327:22)
    at Unpack.[emit] (/home/user/session-desktop/node_modules/better-sqlite3/node_modules/tar/lib/parse.js:285:12)
    at Unpack.[maybeEnd] (/home/user/session-desktop/node_modules/better-sqlite3/node_modules/tar/lib/parse.js:401:17)
    at Unpack.[consumeChunk] (/home/user/session-desktop/node_modules/better-sqlite3/node_modules/tar/lib/parse.js:432:21)
    at Unpack.write (/home/user/session-desktop/node_modules/better-sqlite3/node_modules/tar/lib/parse.js:364:25)
    at Unpack.end (/home/user/session-desktop/node_modules/better-sqlite3/node_modules/tar/lib/parse.js:477:14)
    at Yallist.<anonymous> (/home/user/session-desktop/node_modules/better-sqlite3/node_modules/minipass/index.js:396:18) {
  recoverable: false,
  file: '/home/user/session-desktop/node_modules/better-sqlite3/deps/sqlite3.tar.gz',
  cwd: '/home/user/session-desktop/node_modules/better-sqlite3/build/Release/obj/gen/sqlite3',
  code: 'TAR_BAD_ARCHIVE',
  tarCode: 'TAR_BAD_ARCHIVE'
}
make: *** [deps/locate_sqlite3.target.mk:17: b857c92884e9598d609f6be182a2595df7a8e00f.intermediate] Error 1
rm b857c92884e9598d609f6be182a2595df7a8e00f.intermediate
make: Leaving directory '/home/user/session-desktop/node_modules/better-sqlite3/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/user/.nvm/versions/node/v14.16.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 5.11.0-27-generic
gyp ERR! command "/home/user/.nvm/versions/node/v14.16.0/bin/node" "/home/user/.nvm/versions/node/v14.16.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /home/user/session-desktop/node_modules/better-sqlite3
gyp ERR! node -v v14.16.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! better-sqlite3@7.1.4 build-release: `node-gyp rebuild --release`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the better-sqlite3@7.1.4 build-release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Other information (please complete the following information):**

* Device: Lenovo Legion Y540
* OS: `5.11.0-27-generic #29~20.04.1-Ubuntu`
* Session Version or Git commit hash: 728d5adda13e1c73b6b0df342c887c277e212aec

**Comment by adamwawrzynski** [comment]
I have found solution on another issue: [https://github.com/signalapp/Signal-Desktop/issues/5220](https://github.com/signalapp/Signal-Desktop/issues/5220).

For others folks struggling with this: follow [this guide](https://github.com/signalapp/Signal-Desktop/issues/5220#issuecomment-832088849).
