### ISSUE TITLE
Building from source on Windows results in error

### ISSUE THREAD

**Issue by hugoender** [oxen-io/session-desktop#2272]
**Describe the bug**
Following the build.md instructions for building for Windows I send `npm install yarn --no-save` and get the following errors:
```
C:\Users\Dan\Downloads\session-desktop>npm install yarn --no-save
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: session-desktop@1.8.4
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^0.14.0 || ^15.0.0-0 || ^16.0.0" from emoji-mart@2.11.2
npm ERR! node_modules/emoji-mart
npm ERR!   emoji-mart@"^2.11.2" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\Dan\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Dan\AppData\Local\npm-cache\_logs\2022-04-28T03_57_57_160Z-debug.log

```
**Other information (please complete the following information):**

* Device: PC
* OS: Windows 10
* Node version: tried both 16.15.0 (latest LTS from Node site) and 16.13.0 as shown in .nvmrc file
* Session Version or Git commit hash: 
```
C:\Users\Dan\Downloads\session-desktop>git show
commit 6e2b2d44f836b65e10ccaf0260a78e16ea54f23a (HEAD -> clearnet, origin/clearnet, origin/HEAD)
Merge: bfb33d14c b93201fbe
Author: Audric Ackermann <audric.bilb@gmail.com>
Date:   Wed Apr 27 14:03:37 2022 +1000

    Merge pull request #2270 from Bilb/show-count-messages-deleting-dialog

    When deleting multiple messages, inform the user of the number
```

**Comment by Bilb** [comment]
can you try `npm install --global yarn` instead?

**Comment by hugoender** [comment]
That command seems to have worked but the next command `yarn install --frozen-lockfile` gives a bunch of warnings and then an error:
```
C:\Users\Hugo\Downloads\session-desktop>npm install --global yarn

added 1 package, and audited 2 packages in 830ms

found 0 vulnerabilities

C:\Users\Hugo\Downloads\session-desktop>yarn install --frozen-lockfile
yarn install v1.22.18
[1/6] Validating package.json...
[2/6] Resolving packages...
[3/6] Fetching packages...
[4/6] Linking dependencies...
warning " > emoji-mart@2.11.2" has incorrect peer dependency "react@^0.14.0 || ^15.0.0-0 || ^16.0.0".
warning " > mic-recorder-to-mp3@2.2.2" has unmet peer dependency "webrtc-adapter@>=4.1.1".
warning "rc-slider > rc-util@4.20.1" has incorrect peer dependency "react@^15.0.0 || ^16.0.0".
warning "rc-slider > rc-util@4.20.1" has incorrect peer dependency "react-dom@^15.0.0 || ^16.0.0".
warning " > react-h5-audio-player@3.2.0" has incorrect peer dependency "react@^16.3.0".
warning " > react-h5-audio-player@3.2.0" has incorrect peer dependency "react-dom@^16.3.0".
warning "react-h5-audio-player > @iconify/react@1.1.3" has incorrect peer dependency "react@^16.0.0".
warning " > react-qr-svg@2.2.1" has incorrect peer dependency "react@>= 0.11.2 < 17.0.0".
warning " > react-redux@7.2.1" has incorrect peer dependency "react@^16.8.3".
warning " > react-virtualized@9.22.3" has incorrect peer dependency "react@^15.3.0 || ^16.0.0-alpha".
warning " > react-virtualized@9.22.3" has incorrect peer dependency "react-dom@^15.3.0 || ^16.0.0-alpha".
warning " > styled-components@5.1.1" has unmet peer dependency "react-is@>= 16.8.0".
warning " > grunt-gitinfo@0.1.7" has incorrect peer dependency "grunt@~0.4.5".
warning " > node-loader@2.0.0" has unmet peer dependency "webpack@^5.0.0".
warning " > ts-loader@9.2.8" has unmet peer dependency "webpack@^5.0.0".
warning " > ts-mock-imports@1.3.0" has incorrect peer dependency "typescript@>=2.6.1 < 4".
warning " > tslint-microsoft-contrib@6.0.0" has incorrect peer dependency "typescript@^2.1.0 || ^3.0.0".
[5/6] Building fresh packages...
[1/12] ⠠ better-sqlite3
[8/12] ⠠ @parcel/watcher
[9/12] ⠠ msgpackr-extract
[10/12] ⠠ playwright
error C:\Users\Hugo\Downloads\session-desktop\node_modules\better-sqlite3: Command failed.
Exit code: 1
Command: npm run build-release
Arguments:
Directory: C:\Users\Hugo\Downloads\session-desktop\node_modules\better-sqlite3
Output:
> better-sqlite3@7.5.0 build-release
> node-gyp rebuild --release

gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@16.13.0 | win32 | x64
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\Hugo\Downloads\session-desktop\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\Hugo\Downloads\session-desktop\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at callback (C:\Users\Hugo\Downloads\session-desktop\node_modules\graceful-fs\polyfills.js:295:20)
gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:198:21)
gyp ERR! System Windows_NT 10.0.19044
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Hugo\\Downloads\\session-desktop\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
gyp ERR! cwd C:\Users\Hugo\Downloads\session-desktop\node_modules\better-sqlite3





C:\Users\Hugo\Downloads\session-desktop>
```

**Comment by dement6d** [comment]
getting this same error on Linux 5.17.5-arch1-1

node -v
`v16.13.0`

npm -v
`8.1.0`

pacman -Q git-lfs
`git-lfs 3.1.4-1`

yarn install --frozen-lockfile
```
yarn install v1.22.18
[1/6] Validating package.json...
[2/6] Resolving packages...
[3/6] Fetching packages...
[4/6] Linking dependencies...
warning " > emoji-mart@2.11.2" has incorrect peer dependency "react@^0.14.0 || ^15.0.0-0 || ^16.0.0".
warning " > mic-recorder-to-mp3@2.2.2" has unmet peer dependency "webrtc-adapter@>=4.1.1".
warning "rc-slider > rc-util@4.20.1" has incorrect peer dependency "react@^15.0.0 || ^16.0.0".
warning "rc-slider > rc-util@4.20.1" has incorrect peer dependency "react-dom@^15.0.0 || ^16.0.0".
warning " > react-h5-audio-player@3.2.0" has incorrect peer dependency "react@^16.3.0".
warning " > react-h5-audio-player@3.2.0" has incorrect peer dependency "react-dom@^16.3.0".
warning "react-h5-audio-player > @iconify/react@1.1.3" has incorrect peer dependency "react@^16.0.0".
warning " > react-qr-svg@2.2.1" has incorrect peer dependency "react@>= 0.11.2 < 17.0.0".
warning " > react-redux@7.2.1" has incorrect peer dependency "react@^16.8.3".
warning " > react-virtualized@9.22.3" has incorrect peer dependency "react@^15.3.0 || ^16.0.0-alpha".
warning " > react-virtualized@9.22.3" has incorrect peer dependency "react-dom@^15.3.0 || ^16.0.0-alpha".
warning " > styled-components@5.1.1" has unmet peer dependency "react-is@>= 16.8.0".
warning " > grunt-gitinfo@0.1.7" has incorrect peer dependency "grunt@~0.4.5".
warning " > node-loader@2.0.0" has unmet peer dependency "webpack@^5.0.0".
warning " > ts-loader@9.2.8" has unmet peer dependency "webpack@^5.0.0".
warning " > ts-mock-imports@1.3.0" has incorrect peer dependency "typescript@>=2.6.1 < 4".
warning " > tslint-microsoft-contrib@6.0.0" has incorrect peer dependency "typescript@^2.1.0 || ^3.0.0".
[5/6] Building fresh packages...
[1/12] ⠂ better-sqlite3
[12/12] ⠂ postinstall-prepare
[3/12] ⠂ node-sass
[6/12] ⠂ electron
error /home/demented/repos/session-desktop/node_modules/better-sqlite3: Command failed.
Exit code: 1
Command: npm run build-release
Arguments:
Directory: /home/demented/repos/session-desktop/node_modules/better-sqlite3
Output:
> better-sqlite3@7.5.0 build-release
> node-gyp rebuild --release

gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@16.13.0 | linux | x64
(node:185384) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
gyp info spawn /usr/bin/python2
gyp info spawn args [
gyp info spawn args   '/home/demented/repos/session-desktop/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/demented/repos/session-desktop/node_modules/better-sqlite3/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/demented/repos/session-desktop/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/demented/.node-gyp/16.13.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/demented/.node-gyp/16.13.0',
gyp info spawn args   '-Dnode_gyp_dir=/home/demented/repos/session-desktop/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/demented/.node-gyp/16.13.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/demented/repos/session-desktop/node_modules/better-sqlite3',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/demented/repos/session-desktop/node_modules/better-sqlite3/build'
  TOUCH b857c92884e9598d609f6be182a2595df7a8e00f.intermediate
  ACTION deps_sqlite3_gyp_locate_sqlite3_target_extract_sqlite3 b857c92884e9598d609f6be182a2595df7a8e00f.intermediate
/home/demented/repos/session-desktop/node_modules/better-sqlite3/deps/extract.js:8
process.on('unhandledRejection', (err) => { throw err; });
                                            ^

Error: TAR_BAD_ARCHIVE: Unrecognized archive format
    at Unpack.warn (/home/demented/repos/session-desktop/node_modules/tar/lib/warn-mixin.js:19:40)
    at Unpack.warn (/home/demented/repos/session-desktop/node_modules/tar/lib/unpack.js:189:18)
    at Unpack.<anonymous> (/home/demented/repos/session-desktop/node_modules/tar/lib/parse.js:81:14)
    at Unpack.emit (node:events:402:35)
    at Unpack.[emit] (/home/demented/repos/session-desktop/node_modules/tar/lib/parse.js:285:12)
    at Unpack.[maybeEnd] (/home/demented/repos/session-desktop/node_modules/tar/lib/parse.js:401:17)
    at Unpack.[consumeChunk] (/home/demented/repos/session-desktop/node_modules/tar/lib/parse.js:432:21)
    at Unpack.write (/home/demented/repos/session-desktop/node_modules/tar/lib/parse.js:364:25)
    at Unpack.end (/home/demented/repos/session-desktop/node_modules/tar/lib/parse.js:477:14)
    at Yallist.<anonymous> (/home/demented/repos/session-desktop/node_modules/minipass/index.js:396:18) {
  recoverable: false,
  file: '/home/demented/repos/session-desktop/node_modules/better-sqlite3/deps/sqlite3.tar.gz',
  cwd: '/home/demented/repos/session-desktop/node_modules/better-sqlite3/build/Release/obj/gen/sqlite3',
  code: 'TAR_BAD_ARCHIVE',
  tarCode: 'TAR_BAD_ARCHIVE'
}
make: *** [deps/locate_sqlite3.target.mk:17: b857c92884e9598d609f6be182a2595df7a8e00f.intermediate] Error 1
rm b857c92884e9598d609f6be182a2595df7a8e00f.intermediate
make: Leaving directory '/home/demented/repos/session-desktop/node_modules/better-sqlite3/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/demented/repos/session-desktop/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Linux 5.17.5-arch1-1
gyp ERR! command "/home/demented/.nvm/versions/node/v16.13.0/bin/node" "/home/demented/repos/session-desktop/node_modules/.bin/node-gyp" "rebuild" "--release"
gyp ERR! cwd /home/demented/repos/session-desktop/node_modules/better-sqlite3
```

**Comment by dement6d** [comment]
@hugoender
this fixed it for me
```sh
rm -rf node_modules && yarn cache clean && git lfs install && yarn install --frozen-lockfile
```

**Comment by KeeJef** [comment]
I will reopen this if you are still having issues building @hugoender ?
