### ISSUE TITLE
Stuck on choose a display name

### ISSUE THREAD

**Issue by dement6d** [oxen-io/session-desktop#2289]
**Bug description**
Session fails to begin session after choosing a display name.
Restarting my PC didn't help.

**To Reproduce**
- Build the app
- Run ./release/linux-unpacked/session-desktop
- Create Session ID, Continue, enter display name & click Get started

**Logs**
```
{"name":"log","hostname":"demented","pid":4631,"level":30,"msg":"listening for registration events","time":"2022-05-07T05:51:58.882Z","v":0}
{"name":"log","hostname":"demented","pid":4631,"level":30,"msg":"sql channel error with call removeAll: SqliteError: no such table: messages_fts\n    at Database.exec ([REDACTED]/node_modules/better-sqlite3/lib/methods/wrappers.js:9:14)\n    at removeAll ([REDACTED]/ts/node/sql.js:2308:28)\n    at IpcMainImpl.<anonymous> ([REDACTED]/ts/node/sql_channel.js:21:28)\n    at IpcMainImpl.emit (node:events:390:28)\n    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:10120)\n    at EventEmitter.emit (node:events:390:28)","time":"2022-05-07T05:51:58.956Z","v":0}
{"name":"log","hostname":"demented","pid":4631,"level":30,"msg":"SIGNING UP","time":"2022-05-07T05:52:14.347Z","v":0}
{"name":"log","hostname":"demented","pid":4631,"level":30,"msg":"sql channel error with call removeAll: SqliteError: no such table: messages_fts\n    at Database.exec ([REDACTED]/node_modules/better-sqlite3/lib/methods/wrappers.js:9:14)\n    at removeAll ([REDACTED]/ts/node/sql.js:2308:28)\n    at IpcMainImpl.<anonymous> ([REDACTED]/ts/node/sql_channel.js:21:28)\n    at IpcMainImpl.emit (node:events:390:28)\n    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:10120)\n    at EventEmitter.emit (node:events:390:28)","time":"2022-05-07T05:52:14.387Z","v":0}
{"name":"log","hostname":"demented","pid":4631,"level":30,"msg":"Updating BrowserWindow config: {\"maximized\":false,\"autoHideMenuBar\":false,\"width\":943,\"height\":507,\"x\":966,\"y\":562,\"fullscreen\":false}","time":"2022-05-07T05:53:19.976Z","v":0}
{"name":"log","hostname":"demented","pid":4631,"level":30,"msg":"config/set: Saving ephemeral config to disk","time":"2022-05-07T05:53:19.976Z","v":0}
{"name":"log","hostname":"demented","pid":4631,"level":30,"msg":"Updating BrowserWindow config: {\"maximized\":false,\"autoHideMenuBar\":false,\"width\":943,\"height\":507,\"x\":966,\"y\":562,\"fullscreen\":false}","time":"2022-05-07T05:53:58.271Z","v":0}
{"name":"log","hostname":"demented","pid":4631,"level":30,"msg":"config/set: Saving ephemeral config to disk","time":"2022-05-07T05:53:58.271Z","v":0}
{"name":"log","hostname":"demented","pid":4631,"level":50,"msg":"Top-level unhandled promise rejection: Error: SQL channel job 16 (removeAll) timed out\n    at [REDACTED]/ts/data/dataInit.js:151:66","time":"2022-05-07T05:53:58.923Z","v":0}
{"name":"log","hostname":"demented","pid":4631,"level":30,"msg":"sql channel error with call removeAll: SqliteError: no such table: messages_fts\n    at Database.exec ([REDACTED]/node_modules/better-sqlite3/lib/methods/wrappers.js:9:14)\n    at removeAll ([REDACTED]/ts/node/sql.js:2308:28)\n    at IpcMainImpl.<anonymous> ([REDACTED]/ts/node/sql_channel.js:21:28)\n    at IpcMainImpl.emit (node:events:390:28)\n    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:10120)\n    at EventEmitter.emit (node:events:390:28)","time":"2022-05-07T05:54:14.364Z","v":0}
```

**Other information (please complete the following information):**

* Device: Desktop PC
* OS: Archcraft x86_64 5.17.5-arch1-1
* Git commit hash: 6e2b2d44f836b65e10ccaf0260a78e16ea54f23a

**Comment by PVCmechanic** [comment]
I believe the issue is caused by 7c1707f adding `dropFtsAndTriggers(assertGlobalInstance())` to the start of `cleanUpOldOpengroups()` in `ts/node/sql.ts`. In the case that `(!ourNumber || !ourNumber.value)` (L3463) evaluates to true, the function returns early without calling `rebuildFtsTable(assertGlobalInstance())`. This leaves the database without the fts tables. 

Adding a call to `rebuildFtsTable()` before the early return fixes the issue, although I am unsure if this is the stylistically preferred solution.

**Comment by dement6d** [comment]
> Adding a call to `rebuildFtsTable()` before the early return fixes the issue, although I am unsure if this is the stylistically preferred solution.

awesome, its been fixed in the clearnet branch
