### ISSUE TITLE
Profanity blocked messages it re-tried to send 3 times?

### ISSUE THREAD

**Issue by slrslr** [oxen-io/session-desktop#2626]
I have found this block of text near the time i was trying to send profanity message to a community (PySOGS 0.3.5) from a Session desktop 1.10.4 ( 991ddd1cbaa1948c865b5e8ad9b2b8137f04641c )

```
WARN  ..:03.636Z decodeV4Response - received raw body of type "text/html; charset=utf-8":  filtration rejected message (profanity)
WARN  ..:03.636Z sendViaOnionV4ToNonSnodeRetryable attempt #1 failed. 2 retries left...: sendViaOnionV4ToNonSnodeWithRetries failed with status code: 429. Retrying...
INFO  ..:04.464Z Polled for group([REDACTED]66b)):, got 0 messages back.
WARN  ..:06.218Z sendViaOnionV4ToNonSnodeRetryable attempt #2 failed. 1 retries left...: sendViaOnionV4ToNonSnodeWithRetries failed with status code: 425. Retrying...
WARN  ..:07.718Z sendViaOnionV4ToNonSnodeRetryable attempt #3 failed. 0 retries left...: sendViaOnionV4ToNonSnodeWithRetries failed with status code: 425. Retrying...
WARN  ..:07.718Z sendViaOnionV4ToNonSnodeRetryable failed  sendViaOnionV4ToNonSnodeWithRetries failed with status code: 425. Retrying... true
WARN  ..:07.718Z Failed to send message to open group: [REDACTED] {"attemptNumber":3,"retriesLeft":0}
ERROR ..:07.719Z Message.saveErrors: null Error: sendViaOnionV4ToNonSnodeWithRetries failed with status code: 425. Retrying...
    at result.retries ([REDACTED]/ts/session/onions/onionSend.js:117:23)
    at async RetryOperation._fn ([REDACTED]/node_modules/p-retry/index.js:50:12)
```

Does it mean it attempted 3 times or it is related to other messages? It should be enough to attempt once in case the response is "filtration rejected message (profanity)".

* Device: PC
* OS: Debian AppImage
* Session Version or Git commit hash: 991ddd1cbaa1948c865b5e8ad9b2b8137f04641c

**Comment by KeeJef** [comment]
Yeah from the logs it looks like we might not be handling the filtration rejected message specially. Which we should be doing @Bilb
