### ISSUE TITLE
Database startup error

### ISSUE THREAD

**Issue by T0KY0R41N** [oxen-io/session-desktop#2630]
Database startup error:

Error: db is not set
    at Object.initializeSql ([REDACTED]\ts\node\sql.js:92:19)
    at showMainWindow ([REDACTED]\ts\mains\main_node.js:604:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async App.<anonymous> ([REDACTED]\ts\mains\main_node.js:578:9)
    
    
    Tried reinstalling multiple times, (windows 10), account works fine on other devices

**Comment by yougotwill** [comment]
@T0KY0R41N Can you try following these instructions and let me know if it works? https://github.com/oxen-io/session-desktop/issues/2814#issuecomment-1627863158

**Comment by KeeJef** [comment]
> I get this error whenever I run the app on rocky8, even on a clean first launch. When run on rocky9, first launch also fails (although a different message: `Bus error (core dumped)`), but then works after that... I tested version `1.11.5`

Do you mean that the first ever launch fails, or each startup it fails once before it starts up correctly?
