### ISSUE TITLE
Error db not set

### ISSUE THREAD

**Issue by Dogoj** [oxen-io/session-desktop#2734]
Getting this Error when trying to load from desktop

Error: db is not set
    at Object.initializeSql ([REDACTED]\ts\node\sql.js:93:19)
    at showMainWindow ([REDACTED]\ts\mains\main_node.js:608:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async App.<anonymous> ([REDACTED]\ts\mains\main_node.js:582:9)**

then session failed to start please start from terminal 

please help

![Screenshot 2023-04-11 194628](https://user-images.githubusercontent.com/128523207/231259934-63549d02-3a92-4612-bcd3-e11760d6edaf.png)
![Screenshot 2023-04-11 194700](https://user-images.githubusercontent.com/128523207/231259974-03239d0b-f487-41c4-afb2-473960994881.png)

**Comment by greenpark-code** [comment]
I do realize that this issue has been closed 6 months ago, however I'm getting "Error db not set" launching the latest stable version, 1.11.4 (both from AppImage and .deb package), on Ubuntu 18.04.


![image](https://github.com/oxen-io/session-desktop/assets/74524458/bb404fae-d6be-4270-9201-9e08054bb7d3)

BTW: the "Copy error and quit" button doesn't copy that text into the clipboard.

console output:

```
$ session-desktop 
Set Windows Application User Model ID (AUMID) { appUserModelId: 'com.loki-project.messenger-desktop' }
NODE_ENV production
NODE_APP_INSTANCE undefined
NODE_CONFIG_DIR /opt/Session/resources/app.asar/config
NODE_CONFIG {}
userData: /home/lemon/.config/Session
config/get: Successfully read user config file
config/get: Did not find ephemeral config file, cache is now empty object
making app single instance
[10908:1017/012928.521299:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.portal.Settings.Read: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.freedesktop.portal.Settings' on object at path /org/freedesktop/portal/desktop
{"name":"log","hostname":"PC","pid":10908,"level":30,"msg":"app ready","time":"2023-10-17T04:29:28.553Z","v":0}
{"name":"log","hostname":"PC","pid":10908,"level":30,"msg":"starting version 1.11.4","time":"2023-10-17T04:29:28.553Z","v":0}
{"name":"log","hostname":"PC","pid":10908,"level":30,"msg":"locale is en-US","time":"2023-10-17T04:29:28.557Z","v":0}
initializeSql sqlnode
Made sure db folder exists at: /home/lemon/.config/Session/sql
{"name":"log","hostname":"PC","pid":10908,"level":30,"msg":"migrateDatabase: Migration without cipher change failed /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by [REDACTED].unpacked/node_modules/@signalapp/better-sqlite3/build/Release/better_sqlite3.node)","time":"2023-10-17T04:29:28.564Z","v":0}
{"name":"log","hostname":"PC","pid":10908,"level":30,"msg":"migrateDatabase: migrateSchemaVersion failed {\"code\":\"ERR_DLOPEN_FAILED\"}","time":"2023-10-17T04:29:28.566Z","v":0}
{"name":"log","hostname":"PC","pid":10908,"level":50,"msg":"error {}","time":"2023-10-17T04:29:28.566Z","v":0}
{"name":"log","hostname":"PC","pid":10908,"level":30,"msg":"Database startup error: Error: db is not set\n    at Object.initializeSql ([REDACTED]/ts/node/sql.js:84:19)\n    at showMainWindow ([REDACTED]/ts/mains/main_node.js:612:25)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async App.<anonymous> ([REDACTED]/ts/mains/main_node.js:586:9)","time":"2023-10-17T04:29:28.566Z","v":0}
Gtk-Message: 01:29:28.678: GtkDialog mapped without a transient parent. This is discouraged.
```

And after pressing the button:

```
Unhandled Promise Rejection: Error: neither globalInstance nor initialized is initialized.
    at assertGlobalInstanceOrInstance (/opt/Session/resources/app.asar/ts/node/sqlInstance.js:18:15)
    at getById (/opt/Session/resources/app.asar/ts/node/sql.js:220:66)
    at Object.getItemById (/opt/Session/resources/app.asar/ts/node/sql.js:190:12)
    at getSpellCheckSetting (/opt/Session/resources/app.asar/ts/mains/main_node.js:76:32)
    at showMainWindow (/opt/Session/resources/app.asar/ts/mains/main_node.js:618:46)
    at async App.<anonymous> (/opt/Session/resources/app.asar/ts/mains/main_node.js:586:9)
{"name":"log","hostname":"PC","pid":10908,"level":50,"msg":"Unhandled Promise Rejection: {}","time":"2023-10-17T04:32:39.452Z","v":0}
Gtk-Message: 01:32:39.472: GtkDialog mapped without a transient parent. This is discouraged.

```

**Comment by KeeJef** [comment]
Tracking SES-1314
