### ISSUE TITLE
[BUG] Session won't open on startup

### ISSUE THREAD

**Issue by osprey1122** [oxen-io/session-desktop#2814]
### Code of conduct

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-desktop/blob/master/CODE_OF_CONDUCT.md)

### Self-training on how to write a bug report

- [X] I have learned [how to write a bug report](https://www.browserstack.com/guide/how-to-write-a-bug-report)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi, osprey here, new to github so sorry if the quality of my bug report isn't up to par, please let me know if more details are needed. 

I am currently trying to run the latest session on MacOS Ventura (up to date) and I keep getting these error messages both with and without a VPN. Thank you.

**Initial Error Message**

Database startup error:

Error: db is not set
    at Object.initializeSql ([REDACTED]/ts/node/sql.js:93:19)
    at showMainWindow ([REDACTED]/ts/mains/main_node.js:608:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async App.<anonymous> ([REDACTED]/ts/mains/main_node.js:582:9)

**Then it shows**
Unhandled Promise Rejection

Error: neither globalInstance nor initialized is initialized.
    at assertGlobalInstanceOrInstance ([REDACTED]/ts/node/sql.js:53:15)
    at getById ([REDACTED]/ts/node/sql.js:239:17)
    at Object.getItemById ([REDACTED]/ts/node/sql.js:208:12)
    at getSpellCheckSetting ([REDACTED]/ts/mains/main_node.js:76:32)
    at showMainWindow ([REDACTED]/ts/mains/main_node.js:614:46)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async App.<anonymous> ([REDACTED]/ts/mains/main_node.js:582:9)

Thank you

### Steps To Reproduce

I have deleted session, then redownloaded a handful of times but the same error message shows. 

### Desktop Version

1.10.08

### Anything else?

Running macOS ventura 13.4.1

**Comment by yougotwill** [comment]
Hi @osprey1122 👋 Let's try starting the app from a fresh state.

```
Open Finder.
Press  Cmd+Shift+G.
In the "Go to" address bar enter  ~/Library/Application\ Support.
Backup the Session folder. (Rename it to Session-old or something)
```

Once you have done that open Session again and either link your device or restore your account using your recovery phrase. Let me know how it goes 😄

**Comment by osprey1122** [comment]
worked like a charm. thank you!
